### ISSUE TITLE
Add description, priority and owner fields

### ISSUE THREAD

**Issue by simonezambonim** [johnsusek/praeco#383]
## 🎉 Goal

It would be nice to have fields to add the owner, priority and some description of the rule. 

## 💪 Motivation

  Working in a big team it usually is good to know who was the rule writer and also some description about it, so others may understand the context. Since Elastalert already expects this fields, I wonder if praeco could make it available on front--end

## 📖 Reference (optional)

[Owner](https://elastalert2.readthedocs.io/en/latest/ruletypes.html#owner)
[Priority](https://elastalert2.readthedocs.io/en/latest/ruletypes.html#priority)
[Description](https://elastalert2.readthedocs.io/en/latest/ruletypes.html#description)

## 📎 Tasks (optional)

- [x] Text Field for owners
- [x] Numeric Field for priority
- [x] Text Field for description

**Comment by nsano-rururu** [comment]
We will add it in the next version so that you can set the description, priority, and owner. The priority will be the following UI.

![1](https://user-images.githubusercontent.com/22293449/123480006-b059f780-d63c-11eb-83c6-c290c8912119.PNG)
https://element.eleme.io/#/en-US/component/input-number

**Comment by nsano-rururu** [comment]
The UI looks like this:
![WS000000](https://user-images.githubusercontent.com/22293449/123501204-203ca200-d67e-11eb-879b-e5ca4afbd551.JPG)
![WS000001](https://user-images.githubusercontent.com/22293449/123501206-23379280-d67e-11eb-9b35-d43e9a981c51.JPG)

**Comment by simonezambonim** [comment]
It looks great! 
I would just suggest making the description field a bit larger.

Thanks for this!

**Comment by nsano-rururu** [comment]
![WS000002](https://user-images.githubusercontent.com/22293449/123511523-b4c5f500-d6bc-11eb-8422-eb894bd82eb6.JPG)

**Comment by nsano-rururu** [comment]
The docker image creation for the next version of praeco will be done at the same time as the next version of elastalert2 is released and the docker image for elastalert-server will be updated.
